#secret: is the name of file containing the secret relative to "config/default.yaml -> passwordDir"
telegram-token: '554104109:AAFMjFpH_uSI935PT9meN6KXnGiyeRda8BM'
# Token to access ccb through telegram
# Setup: in telegram sent the following messages to BotFather user:
# /start
# /newbot
# /<botname>
# /<arbitrary_username_ending_with_bot>
# In the reply you will get  "Use this token to access the HTTP API: 
# Paste this to telegram-token blow!
# start telegram access call 'bin/index.js'
# In telegram write message to <botname>
# eg: /ls
# This will list the contents of the dir. 
# You have full bash access from telegram.
# And thus a huge security hole!!!! Beware!

keys:
  #name of exchanges can be any that is supported by ccxt
  kucoin:
    type: 'centralized'
    apiKey: 'KqI537O8OEvRAUJF'
    #secret: is the name of file containing the secret relative to "config/default.yaml -> passwordDir"
    secret: 'filename.pw' #filename
    timeout: 30000
    enableRateLimit: true
  # further exchanges can be added here. Supported exchanges: https://www.npmjs.com/package/ccxt
  # Use their id in here from the link.
withdraw:
  kucoin:
    USD: # currency to withdraw
      HSBC: # name of bank account that has been set on exchange
        destination: 'HSBC'
        params:
          key: 'HSBC-USD' # extra params can be added, see at each exchange API doc for details
    ETH:
      ACC1:
        destination: '0xffffffffffffffffffffffffffffffffffffffff'
        params:
          key: 'binance'
  # add further withdraw data here
web3:
  etherscan: 
    # Needed for auto-downloading abi for smart contracts. 
    # You do not need to have api-key if you already have 
    # an entry for contract in './abi/' folder.
    #api-key: is the name of file containing the secret relative to "config/default.yaml -> passwordDir"
    api-key: 'etherscan.api-key' #filename
  ethgasstation: 
    # api-key required for auto gas estimation.
    # If you provide --gaslimit every time, then you 
    # do not need to fill in api-key below.
    #api-key: is the name of file containing the secret relative to "config/default.yaml -> passwordDir"
    api-key: 'ethgasstation.api-key' #filename
  account: 
    # List all your accounts below. 
    # Account names are arbitrary. 
    # They will be substituted with address 
    # specified at address: field.
    #you can choose any name accepted by yaml fromat
    ETH-A:
      address: '0xBBFa02584B9beb9FA258e3f986eF79825BFbBC5F'
      type: 'privatekey'
      #privatekey: is the name of file containing the secret relative to "config/default.yaml -> passwordDir"
      privatekey: 'privatekey.filename' #filename
      remark: ''
    ETH-B: 
      address: '0xFF8468FF7ea1e4e69414F004FED974F1E07d4e4b'
      #type: 'privatekey', if you provide private key (not safe)
      #type: 'airsign', if you use sealed phone and QR codes https://github.com/r001/airsign
      #type: 'ledger', if you use https://ledger.com cold wallet
      type: 'airsign'
      #privatekey: is the name of file containing the secret relative to "config/default.yaml -> passwordDir"
      privatekey: ''
    ETH-C:
      address: '0xCC8468CC7ea1e4e69414C004CED974C1E07d4e4b'
      type: 'ledger'
      #derivePath: optional makes queries faster. You can get its value issuing: `cceb ledger addresses`
      derivePath: "44'/60'/0'/0" 
  networks:
    mainnet:
      aave:
        referralCode: 0
      provider:
        infura: 
          # To access ethereum you do need a provider, that is usually
          # infura. Get an api-key for free at https://infura.io
          # api-key: filename of the api key for infura.io relative to "config/default.yaml -> passwordDir"
          api-key: 'infura.api-key' #filename
        alchemy:
          api-key: 'alchemy.api-key' #filename
      deposit:
        # deposit addresses must be in the form <upper_case_exchange_name>_<upper_case_token_name>
        # now you can issue:
        # ./ccb eth tx ETH transfer BINANCE_ETH 1.000000000000000000 --from ETH-1
        # If destination address is a deposit address, 
        # cceb will check if it can receive the token transferred. 
        # This is to avoid to send token to the wrong deposit address.
        KUCOIN_ETH:
          address: '0xb6fbbae826c82f2eb44fdee032bb8b2a6609b2fa'
        KUCOIN_USDT:
          address: '0xb6fbbae826c82f2eb44fdee032bb8b2a6609b2fa'
        KUCOIN_CRV:
          address: '0xb6fbbae826c82f2eb44fdee032bb8b2a6609b2fa'
        KUCOIN_ENG:
          address: '0xb6fbbae826c82f2eb44fdee032bb8b2a6609b2fa'
    rinkeby:
      provider:
        infura:
          api-key: 'infura.api-key' #filename
    kovan:
      provider:
        infura:
          api-key: 'infura.api-key' #filename
    ropsten:
      provider:
        infura:
          api-key: 'infura.api-key' #filename
